AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create Lambda function, EventBridge Rule for 15-min trigger

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler  # Handler function in Lambda code (make sure it matches)
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: "taskuserdata"  # Replace with your S3 bucket name
        S3Key: "currentTime.zip"  # Replace with the correct S3 object key
      Runtime: nodejs22.x  # Set the runtime for your function (adjust if needed)
      Timeout: 15

  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(15 minutes)  # This triggers the Lambda function every 15 minutes
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: LambdaTarget

  LambdaPermissionForEventBridge:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventBridgeRule.Arn
