AWSTemplateFormatVersion: '2010-09-09'
Description: VPC and Networking Resources for ECS

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where ECS will run.
    Default: vpc-001909eff2f25c897  # Your VPC ID

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: A list of subnets for ECS tasks, NLB, and API Gateway.
    Default:
      - subnet-06f641326b15e35f1
      - subnet-07c96a8bc347064e9
      - subnet-0a8d8d15fd2251b3f
      - subnet-0d46a5192b018fefb
      - subnet-091fbb697e19ff92e
      - subnet-07fbe67094889ea4a

Resources:
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic to ECS tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  ECSSecurityGroupId:
    Description: The security group ID for ECS tasks.
    Value: !Ref ECSSecurityGroup
