version: 0.2

env:
  variables:
    APPLICATION_NAME: "ecs-fargate"

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      nodejs: 14
    commands:
      - echo "Verifying installed .NET SDK and Docker versions..."
      - dotnet --version
      - docker --version
      - echo "Environment setup complete."

  pre_build:
    commands:
      - echo "Checking available files..."
      - echo "Pre-build started on `date`"
      - dotnet nuget locals all --clear  # Clear NuGet cache
      - dotnet restore # Restore dependencies

  build:
    commands:
      - echo "Building .NET application..."
      - dotnet build ecs-fargate/ecs-fargate.sln --configuration Release
      - echo "Publishing .NET application..."
      - dotnet publish ecs-fargate/ecs-fargate.sln --configuration Release --output ecs-fargate/publish_output

      - echo "Building Docker image..."
      - docker build -t simple-docker-service-0afff1e6c27f:latest -f ecs-fargate/Dockerfile ecs-fargate/
      
      - echo "Tagging Docker image..."
      - docker tag simple-docker-service-0afff1e6c27f:latest 640168412115.dkr.ecr.us-east-1.amazonaws.com/simple-docker-service-0afff1e6c27f:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 640168412115.dkr.ecr.us-east-1.amazonaws.com/simple-docker-service-0afff1e6c27f:latest
      - echo "Build and push completed on `date`"

      # Deploy static files to S3
      - echo "Deploying application files to S3..."
      - aws s3 cp ecs-fargate/publish_output s3://staticwerbsite-deploy-codepipeline --recursive --exclude ".git/*" --exclude "buildspec.yml"

artifacts:
  files:
    - '**/*'
